[versions]
assertj-core = "3.27.6"
checkstyle = "12.3.0"
jacoco = "0.8.14"
javafxplugin = "0.1.0"
junit-jupiter = "6.0.2"
pmd = "7.16.0"
spring-boot = "4.0.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
htmlunit = { module = "org.htmlunit:htmlunit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc", version.ref = "spring-boot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "spring-boot" }

[plugins]
javafxplugin = { id = "org.openjfx.javafxplugin", version.ref = "javafxplugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
